name: Generate Datas Snake Readme

on:
  schedule:
    - cron: "* */12 * * *"  # Executa a cada 12h
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          pip install matplotlib numpy

      - name: Generate Snake Animation
        run: |
          git clone https://github.com/Platane/snk.git
          cd snk
          python3 main.py --user ${{ github.repository_owner }} --output ../github-contribution-grid-snake.svg

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generated snake animation"
          branch: output
