name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Checkout do código
      - name: Checkout
        uses: actions/checkout@v3

      # Gerar animação da cobrinha
      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: brunsoares  # Substitua pelo seu nome de usuário
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Verificar a criação do SVG
      - name: List files in dist directory
        run: ls -alh dist

      # Verificar conteúdo do SVG gerado
      - name: Check SVG output
        run: |
          cat dist/github-contribution-grid-snake.svg

      # Commit e push do arquivo gerado
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generated snake animation"
          branch: output

      # Publicar no GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
